#!/usr/bin/env python3
"""Regenerate the root README and everything in indexes/.

These files are pure functions of data/manifest.json, so they are rendered by a
deterministic script rather than written by the annotator. Two reasons:

  * idempotency comes for free — running twice in one day produces byte-identical
    output, which is what makes Job 2 safe to re-run;
  * a model hand-maintaining index tables is a source of drift, and there is no
    judgement involved in sorting rows.

Job 2 writes the prose (each problem README and the comments in solution.py) and
then runs this. Dates are computed from UTC calendar days, not from seconds, so
output only changes when the day changes.

Run: /usr/bin/python3 scripts/render_indexes.py
"""

import json
import os
import re
import subprocess
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MANIFEST = REPO / "data" / "manifest.json"
INDEXES = REPO / "indexes"

DIFFICULTY_ORDER = {"Easy": 0, "Medium": 1, "Hard": 2}

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/render_indexes.py from data/manifest.json. "
    "Hand edits are overwritten on the next run. -->"
)

# Revisit at 1, 3, 7 and 30 days. No per-problem review state is stored
# anywhere: the bucket is derived from how long ago the problem was solved.
BUCKETS = [
    (0, 1, "Solved today"),
    (1, 3, "1-3 days ago"),
    (3, 7, "3-7 days ago"),
    (7, 30, "7-30 days ago"),
    (30, None, "30+ days ago - most likely to have faded"),
]


def load():
    if not MANIFEST.exists():
        return {}
    return json.loads(MANIFEST.read_text(encoding="utf-8")).get("problems", {})


def folder(entry) -> str:
    fid = entry["frontendId"]
    padded = fid.zfill(4) if fid.isdigit() else fid
    return "%s-%s" % (padded, entry["slug"])


def link(entry) -> str:
    return "[%s. %s](problems/%s/README.md)" % (
        entry["frontendId"],
        entry["title"],
        folder(entry),
    )


def index_link(entry) -> str:
    return "[%s. %s](../problems/%s/README.md)" % (
        entry["frontendId"],
        entry["title"],
        folder(entry),
    )


def solved_date(entry) -> str:
    return datetime.fromtimestamp(entry["timestamp"], tz=timezone.utc).strftime("%Y-%m-%d")


def days_since(entry, today) -> int:
    solved = datetime.fromtimestamp(entry["timestamp"], tz=timezone.utc).date()
    return (today - solved).days


def by_number(problems):
    return sorted(
        problems.values(),
        key=lambda e: int(e["frontendId"]) if e["frontendId"].isdigit() else 10**9,
    )


BADGE = "https://img.shields.io/badge"
FALLBACK_SLUG = "yadava5/leetloop"


def repo_slug() -> str:
    """`owner/name`, read from git rather than hardcoded.

    A fork gets working CI badges and links with no edit to this file, which is
    one less thing for someone to have to notice.
    """
    env = os.environ.get("GITHUB_REPOSITORY")
    if env and "/" in env:
        return env
    try:
        url = subprocess.run(
            ["/usr/bin/git", "remote", "get-url", "origin"],
            cwd=REPO,
            capture_output=True,
            text=True,
            timeout=10,
        ).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return FALLBACK_SLUG
    # git@github.com:owner/name.git  or  https://github.com/owner/name.git
    match = re.search(r"[:/]([^/:]+/[^/]+?)(?:\.git)?$", url)
    return match.group(1) if match else FALLBACK_SLUG


REPO_SLUG = repo_slug()


def badges(problems) -> list:
    """Shields.io badges as raw HTML.

    HTML, not markdown image syntax, because these sit inside a centred
    `<p align="center">` block and GitHub does not parse markdown inside a
    block-level HTML element — the markdown version renders as literal text.

    The counts are computed from the manifest on every run, so they cannot drift
    away from what the repo actually contains.
    """
    counts = defaultdict(int)
    for entry in problems.values():
        counts[entry["difficulty"]] += 1
    topics = {topic for entry in problems.values() for topic in entry["topics"]}

    # No `str | None` annotation here: the local interpreter is Python 3.9, where
    # PEP 604 unions in annotations are evaluated at runtime and raise TypeError.
    def img(alt, src, href=""):
        tag = '<img alt="%s" src="%s">' % (alt, src)
        return '<a href="%s">%s</a>' % (href, tag) if href else tag

    workflow = "https://github.com/%s/actions/workflows/fetch.yml" % REPO_SLUG

    return [
        img("daily fetch status", workflow + "/badge.svg", workflow),
        img(
            "code unmodified: AST-verified",
            "%s/code%%20unmodified-AST--verified-2ea44f" % BADGE,
            "scripts/verify_ast.py",
        ),
        img("problems solved", "%s/problems-%d-1f6feb" % (BADGE, len(problems))),
        img("easy", "%s/easy-%d-00b8a3" % (BADGE, counts["Easy"])),
        img("medium", "%s/medium-%d-ffb800" % (BADGE, counts["Medium"])),
        img("hard", "%s/hard-%d-ff375f" % (BADGE, counts["Hard"])),
        img("topics covered", "%s/topics-%d-8957e5" % (BADGE, len(topics))),
        img("solutions in Python 3", "%s/solutions-Python%%203-3572A5" % BADGE),
        img("pipeline in TypeScript", "%s/pipeline-TypeScript-3178c6" % BADGE),
        img("Anthropic API keys required: 0", "%s/Anthropic%%20API%%20keys-0-lightgrey" % BADGE),
        img("MIT license", "%s/license-MIT-blue" % BADGE, "LICENSE"),
    ]


PIPELINE_DIAGRAM = """```mermaid
flowchart LR
    subgraph you["you"]
        SOLVE["solve a problem<br/>on leetcode.com"]
        REVISE["open the problem page<br/>and redo it cold"]
    end

    subgraph job1["Job 1 · fetch — 17:00 UTC · GitHub Action"]
        FETCH["submissionList<br/>since lastSyncedTimestamp"]
        HYDRATE["submissionDetails + question<br/>1 req/sec, 3ⁿ backoff"]
        STRIP["drop content + hints<br/>copyrighted, repo is public"]
        RAW["data/raw/&lt;slug&gt;.py<br/>verbatim · source of truth"]
        META["data/questions/&lt;slug&gt;.json"]
    end

    subgraph job2["Job 2 · annotate — 18:00 UTC · Claude routine"]
        PENDING{"anything with<br/>annotated: false?"}
        WRITE["write solution.py + README.md<br/>comments and prose only"]
        GATE{"AST gate<br/>verify_ast.py"}
        RENDER["render_indexes.py<br/>root README + indexes/"]
        DISCARD["discard output<br/>leave entry pending"]
    end

    PAGES["problems/&lt;n&gt;-&lt;slug&gt;/<br/>README.md + solution.py"]
    MANIFEST[("data/manifest.json<br/>the only shared state")]

    SOLVE --> FETCH --> HYDRATE --> STRIP --> RAW & META
    RAW & META --> MANIFEST
    MANIFEST --> PENDING
    PENDING -- "no" --> STOP["stop · commit nothing"]
    PENDING -- "yes" --> WRITE --> GATE
    GATE -- "AST equal — comments only" --> RENDER --> PAGES
    GATE -- "anything else changed" --> DISCARD
    PAGES --> MANIFEST
    PAGES --> REVISE --> SOLVE

    classDef human fill:#1f6feb22,stroke:#1f6feb,stroke-width:1px
    classDef gate fill:#2ea44f22,stroke:#2ea44f,stroke-width:1px
    classDef bad fill:#ff375f22,stroke:#ff375f,stroke-width:1px
    class SOLVE,REVISE human
    class GATE,PENDING gate
    class DISCARD bad
```"""


def render_root(problems) -> str:
    rows = []
    for entry in by_number(problems):
        pct = (
            " (top %d%%)" % round(100 - entry["runtimePercentile"])
            if entry.get("runtimePercentile")
            else ""
        )
        rows.append(
            "| %s | %s | %s | %s | %s | %s%s |"
            % (
                entry["frontendId"],
                link(entry),
                entry["difficulty"],
                ", ".join(entry["topics"]),
                solved_date(entry),
                entry["runtime"],
                pct,
            )
        )

    counts = defaultdict(int)
    for entry in problems.values():
        counts[entry["difficulty"]] += 1
    tally = " · ".join(
        "%s %d" % (name, counts[name]) for name in ("Easy", "Medium", "Hard") if counts[name]
    )

    return "\n".join(
        [
            GENERATED_NOTE,
            "",
            '<p align="center">',
            "  <picture>",
            '    <source media="(prefers-color-scheme: dark)" srcset="assets/logo-dark.svg">',
            '    <source media="(prefers-color-scheme: light)" srcset="assets/logo-light.svg">',
            '    <img alt="leetloop" src="assets/logo-light.svg" width="420">',
            "  </picture>",
            "</p>",
            "",
            '<p align="center">',
            "  <strong>A LeetCode revision surface that fills itself.</strong><br>",
            "  I solve a problem; by the next afternoon this repo holds a page that gets me",
            "  back into it months later — the idea that unlocks it, why this approach beats",
            "  the obvious one, the traps, and a checklist for rebuilding it from nothing.",
            "</p>",
            "",
            '<p align="center">',
            "  " + " ".join(badges(problems)),
            "</p>",
            "",
            "**%d problem%s** — %s. Solutions in Python."
            % (len(problems), "" if len(problems) == 1 else "s", tally or "none yet"),
            "",
            "---",
            "",
            "## The loop",
            "",
            '<p align="center">',
            "  <picture>",
            '    <source media="(prefers-color-scheme: dark)" srcset="assets/pipeline-dark.svg">',
            '    <source media="(prefers-color-scheme: light)" srcset="assets/pipeline-light.svg">',
            '    <img alt="Ayush solves a problem on leetcode.com. Job 1, a GitHub Action at '
            "17:00 UTC holding the LeetCode session cookie and calling no AI model, commits "
            "the submission verbatim to data/raw. Across a security boundary the cookie never "
            "crosses, Job 2, a scheduled Claude routine at 18:00 UTC holding no credentials "
            "and no API key, writes a revision page. An AST gate then checks ast(raw) == "
            "ast(new): equal trees commit the page, differing trees discard it and commit "
            'nothing. Ayush reopens the page later and solves it again, cold." '
            'src="assets/pipeline-light.svg">',
            "  </picture>",
            "</p>",
            "",
            "<details>",
            "<summary>Same thing as a Mermaid flowchart, if you'd rather read the graph</summary>",
            "",
            PIPELINE_DIAGRAM,
            "",
            "</details>",
            "",
            "Two scheduled jobs, and the split between them is the interesting part.",
            "",
            "| | Job | Runs on | Holds | Daily at |",
            "| --- | --- | --- | --- | --- |",
            "| **1** | **fetch** — pull new submissions, commit raw code | GitHub Action, no model involved | the LeetCode cookie | `17:00 UTC` |",
            "| **2** | **annotate** — write the notes, verify, commit | Claude scheduled routine | no credentials at all | `18:00 UTC` |",
            "",
            "Each job holds exactly one of the two sensitive things and never needs the",
            "other's. Job 1 keeps the session cookie in GitHub's encrypted secret store and",
            "never talks to a model. Job 2 has no credentials because the scheduled agent",
            "*is* the model — which is why **this system contains no Anthropic API key, and",
            "is designed so that it never needs one.**",
            "",
            "## The guarantee: my code is provably unmodified",
            "",
            "An LLM writes the commentary, so \"it didn't touch my code\" has to be *checked*,",
            "not promised. [`scripts/verify_ast.py`](scripts/verify_ast.py) parses the raw",
            "submission and the annotated copy and compares",
            "`ast.dump(tree, annotate_fields=True, include_attributes=False)`.",
            "",
            "Python's parser discards comments and blank lines entirely, so they cannot",
            "appear in an AST. **Equal dumps therefore prove every byte of difference is a",
            "comment or whitespace.** A renamed variable, a reordered statement, a changed",
            "literal, an added docstring or a helpfully-fixed bug each change the dump, and",
            "the annotation is discarded instead of committed.",
            "",
            "It's checked in both directions — a gate that only ever passes is not a gate.",
            "[`scripts/test_verify_ast.py`](scripts/test_verify_ast.py) asserts 3 cases that",
            "must pass and 5 that must fail, plus the README's inline copy of each solution,",
            "and CI runs it on every fetch.",
            "",
            "```",
            "  [ok] gate said PASS, expected PASS   comments and blank lines only",
            "  [ok] gate said PASS, expected PASS   comment on nearly every line",
            "  [ok] gate said FAIL, expected FAIL   one renamed variable (seen -> cache)",
            "  [ok] gate said FAIL, expected FAIL   docstring added",
            "  [ok] gate said FAIL, expected FAIL   two statements reordered",
            "  [ok] gate said FAIL, expected FAIL   return [] changed to return None",
            "  [ok] gate said FAIL, expected FAIL   annotated file does not parse",
            "```",
            "",
            "## Problems",
            "",
            "| # | Problem | Difficulty | Topics | Solved | Runtime |",
            "| --: | --- | --- | --- | --- | --- |",
            *rows,
            "",
            "Other views: **[by topic](indexes/by-topic.md)** ·",
            "**[by difficulty](indexes/by-difficulty.md)** ·",
            "**[review queue](indexes/review-queue.md)** — spaced repetition with no",
            "bookkeeping, bucketed by how long ago each problem was solved.",
            "",
            "## What a problem page contains",
            "",
            "Not a code dump. Each [`problems/<n>-<slug>/README.md`](problems) is",
            "self-contained and has nine sections:",
            "",
            "1. **Header** — difficulty, topics, date solved, runtime and memory percentiles,",
            "   link to the original.",
            "2. **The problem** — given / return / guaranteed, plus the method signature.",
            "3. **Examples** — invented, with a one-line *why* each, including a",
            "   counterexample to the naive approach.",
            "4. **Constraints, and what each one forces** — every row says what the",
            "   constraint rules in or out, not just the number again.",
            "5. **Key insight** — the one thing I'd want whispered to me if stuck.",
            "6. **Approach** — the walk-through, flagging any step whose *order* is",
            "   load-bearing.",
            "7. **Solution** — the annotated code inline, AST-verified against the raw",
            "   submission like `solution.py` itself.",
            "8. **Why this approach** — the realistic alternatives, each with the specific",
            "   reason this beats it.",
            "9. **Complexity · Pitfalls · Redo from scratch · Related problems.**",
            "",
            "## Layout",
            "",
            "```",
            "problems/<n>-<slug>/    GENERATED — the revision page + annotated solution",
            "indexes/                GENERATED — by topic, by difficulty, review queue",
            "data/raw/<slug>.py      my submission, verbatim — the gate's reference copy",
            "data/questions/*.json   cached metadata, with LeetCode's prose stripped out",
            "data/manifest.json      the only shared state between the two jobs",
            "src/                    Job 1 — TypeScript ESM, zero runtime dependencies",
            "scripts/verify_ast.py   the gate — plain Python, no dependencies",
            "docs/routine-prompt.txt Job 2 — the entire prompt, version-controlled",
            "```",
            "",
            "Anything marked GENERATED is rewritten on every run; hand edits vanish.",
            "",
            "## Fork it and point it at your own account",
            "",
            "It is built to be forked — nothing about the pipeline is specific to me except",
            "the contents of `data/`. **[docs/FORKING.md](docs/FORKING.md) is the full",
            "walkthrough**; the shape of it is:",
            "",
            "1. **Fork**, then wipe my data — `data/`, `problems/`, `indexes/` — and reset the",
            "   manifest to empty. One block of commands in the guide.",
            "2. **Add two secrets** from your own browser: `LEETCODE_SESSION` and",
            "   `LEETCODE_CSRF_TOKEN`. This is the only credential in the system.",
            "3. **Enable Actions.** GitHub disables scheduled workflows in forks until you turn",
            "   them on, so this step is easy to miss and looks like a silent failure.",
            "4. **Create the annotation routine** at <https://claude.ai/code/routines>, pasting",
            "   [`docs/routine-prompt.txt`](docs/routine-prompt.txt). Needs a Claude plan that",
            "   includes scheduled routines — this is the one part you can't substitute without",
            "   reintroducing an API key.",
            "5. **Solve something** and wait for the next 17:00 UTC.",
            "",
            "You do not need to edit any code: the CI badge and links derive the repo slug from",
            "your git remote, and the committer name and email come from repository variables",
            "with sensible defaults. **If you solve in a language other than Python, read the",
            "gate section of the guide first** — AST equality is exact only because Python",
            "discards comments at parse time, and the gate deliberately refuses to guess for",
            "other languages.",
            "",
            "## Docs",
            "",
            "- **[docs/ARCHITECTURE.md](docs/ARCHITECTURE.md)** — the secret boundary, the",
            "  three fetch stages, exit codes, the manifest schema, and what a non-Python",
            "  language would need instead of AST equality.",
            "- **[docs/RUNBOOK.md](docs/RUNBOOK.md)** — the LeetCode session cookie expires",
            "  every 1–2 weeks and cannot be refreshed programmatically, so the pipeline",
            "  files a GitHub issue and emails me. Fixing it is two commands.",
            "- **[docs/ROUTINE.md](docs/ROUTINE.md)** — how Job 2 is scheduled and how to",
            "  change its prompt safely.",
            "- **[docs/FORKING.md](docs/FORKING.md)** — running your own copy end to end.",
            "",
            "## Credits",
            "",
            "The logo and the pipeline diagram in this README are original SVGs — animated with",
            "CSS inside the file, one variant per colour scheme, no JavaScript, since GitHub",
            "sanitises scripts out of rendered markdown. They live in",
            "[`assets/`](assets) and are MIT-licensed along with everything else here, so reuse",
            "them if they're useful.",
            "",
            "## On copyright",
            "",
            "LeetCode's problem statements are theirs, and this repo is public. Job 1 never",
            "persists the statement or the hints; Job 2 reads the statement at annotate time",
            "and writes only its own restatement, with my own examples. A pre-commit hook",
            "blocks that prose from reappearing, because history here is append-only and a",
            "leak committed once could not be taken back.",
            "",
            "MIT licensed — the notes and the pipeline, not the problems.",
            "",
        ]
    )


def render_by_topic(problems) -> str:
    topics = defaultdict(list)
    for entry in problems.values():
        for topic in entry["topics"]:
            topics[topic].append(entry)

    lines = ["# By topic", "", GENERATED_NOTE, ""]
    if not topics:
        lines += ["Nothing solved yet.", ""]
        return "\n".join(lines)

    for topic in sorted(topics, key=lambda t: (-len(topics[t]), t)):
        entries = sorted(
            topics[topic],
            key=lambda e: int(e["frontendId"]) if e["frontendId"].isdigit() else 10**9,
        )
        lines.append("## %s (%d)" % (topic, len(entries)))
        lines.append("")
        for entry in entries:
            lines.append("- %s — %s" % (index_link(entry), entry["difficulty"]))
        lines.append("")
    return "\n".join(lines)


def render_by_difficulty(problems) -> str:
    groups = defaultdict(list)
    for entry in problems.values():
        groups[entry["difficulty"]].append(entry)

    lines = ["# By difficulty", "", GENERATED_NOTE, ""]
    if not groups:
        lines += ["Nothing solved yet.", ""]
        return "\n".join(lines)

    for difficulty in sorted(groups, key=lambda d: DIFFICULTY_ORDER.get(d, 99)):
        entries = sorted(
            groups[difficulty],
            key=lambda e: int(e["frontendId"]) if e["frontendId"].isdigit() else 10**9,
        )
        lines.append("## %s (%d)" % (difficulty, len(entries)))
        lines.append("")
        for entry in entries:
            lines.append(
                "- %s — %s" % (index_link(entry), ", ".join(entry["topics"]))
            )
        lines.append("")
    return "\n".join(lines)


def render_review_queue(problems) -> str:
    today = datetime.now(tz=timezone.utc).date()
    buckets = defaultdict(list)
    for entry in problems.values():
        age = days_since(entry, today)
        for low, high, label in BUCKETS:
            if age >= low and (high is None or age < high):
                buckets[label].append((age, entry))
                break

    lines = [
        "# Review queue",
        "",
        GENERATED_NOTE,
        "",
        "Spaced repetition without any bookkeeping: problems are bucketed purely by how",
        "long ago they were solved, so there is no review state to keep up to date. The",
        "useful habit is to revisit a problem about 1, 3, 7 and 30 days after solving it.",
        "",
        "Work top-down: redo the problem from the **Redo from scratch** checklist in its",
        "README without reading the code first.",
        "",
        "Generated for %s (UTC)." % today.isoformat(),
        "",
    ]

    for _, _, label in BUCKETS:
        entries = sorted(buckets.get(label, []), key=lambda pair: -pair[0])
        lines.append("## %s (%d)" % (label, len(entries)))
        lines.append("")
        if not entries:
            lines.append("_nothing here_")
            lines.append("")
            continue
        for age, entry in entries:
            lines.append(
                "- %s — %s, %s — solved %s (%d day%s ago)"
                % (
                    index_link(entry),
                    entry["difficulty"],
                    ", ".join(entry["topics"]),
                    solved_date(entry),
                    age,
                    "" if age == 1 else "s",
                )
            )
        lines.append("")

    return "\n".join(lines)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not text.endswith("\n"):
        text += "\n"
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    path.write_text(text, encoding="utf-8")
    print("%s  %s" % ("unchanged" if existing == text else "written  ", path.relative_to(REPO)))


def main() -> int:
    problems = load()
    write(REPO / "README.md", render_root(problems))
    write(INDEXES / "by-topic.md", render_by_topic(problems))
    write(INDEXES / "by-difficulty.md", render_by_difficulty(problems))
    write(INDEXES / "review-queue.md", render_review_queue(problems))
    print("rendered %d problem(s)" % len(problems))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
