#!/usr/bin/env python3
"""Regenerate the root README and everything in indexes/.

These files are pure functions of data/manifest.json, so they are rendered by a
deterministic script rather than written by the annotator. Two reasons:

  * idempotency comes for free — running twice in one day produces byte-identical
    output, which is what makes Job 2 safe to re-run;
  * a model hand-maintaining index tables is a source of drift, and there is no
    judgement involved in sorting rows.

Job 2 writes the prose (each problem README and the comments in solution.py) and
then runs this. Dates are computed from UTC calendar days, not from seconds, so
output only changes when the day changes.

Run: /usr/bin/python3 scripts/render_indexes.py
"""

import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MANIFEST = REPO / "data" / "manifest.json"
INDEXES = REPO / "indexes"

DIFFICULTY_ORDER = {"Easy": 0, "Medium": 1, "Hard": 2}

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/render_indexes.py from data/manifest.json. "
    "Hand edits are overwritten on the next run. -->"
)

# Revisit at 1, 3, 7 and 30 days. No per-problem review state is stored
# anywhere: the bucket is derived from how long ago the problem was solved.
BUCKETS = [
    (0, 1, "Solved today"),
    (1, 3, "1-3 days ago"),
    (3, 7, "3-7 days ago"),
    (7, 30, "7-30 days ago"),
    (30, None, "30+ days ago - most likely to have faded"),
]


def load():
    if not MANIFEST.exists():
        return {}
    return json.loads(MANIFEST.read_text(encoding="utf-8")).get("problems", {})


def folder(entry) -> str:
    fid = entry["frontendId"]
    padded = fid.zfill(4) if fid.isdigit() else fid
    return "%s-%s" % (padded, entry["slug"])


def link(entry) -> str:
    return "[%s. %s](problems/%s/README.md)" % (
        entry["frontendId"],
        entry["title"],
        folder(entry),
    )


def index_link(entry) -> str:
    return "[%s. %s](../problems/%s/README.md)" % (
        entry["frontendId"],
        entry["title"],
        folder(entry),
    )


def solved_date(entry) -> str:
    return datetime.fromtimestamp(entry["timestamp"], tz=timezone.utc).strftime("%Y-%m-%d")


def days_since(entry, today) -> int:
    solved = datetime.fromtimestamp(entry["timestamp"], tz=timezone.utc).date()
    return (today - solved).days


def by_number(problems):
    return sorted(
        problems.values(),
        key=lambda e: int(e["frontendId"]) if e["frontendId"].isdigit() else 10**9,
    )


def render_root(problems) -> str:
    rows = []
    for entry in by_number(problems):
        rows.append(
            "| %s | %s | %s | %s | %s | %s |"
            % (
                entry["frontendId"],
                link(entry),
                entry["difficulty"],
                ", ".join(entry["topics"]),
                solved_date(entry),
                entry["runtime"],
            )
        )

    counts = defaultdict(int)
    for entry in problems.values():
        counts[entry["difficulty"]] += 1
    tally = " · ".join(
        "%s %d" % (name, counts[name]) for name in ("Easy", "Medium", "Hard") if counts[name]
    )

    return "\n".join(
        [
            "# LeetCode revision notes",
            "",
            GENERATED_NOTE,
            "",
            "Not an archive — a revision surface. Each problem folder holds the idea that",
            "unlocks the problem, why this approach beats the obvious one, the pitfalls, and",
            "a checklist for rebuilding it cold.",
            "",
            "Solutions are in Python. `problems/<n>-<slug>/solution.py` is the exact code I",
            "submitted plus explanatory comments — and that is *proved*, not asserted:",
            "[`scripts/verify_ast.py`](scripts/verify_ast.py) compares the abstract syntax",
            "trees of the annotated file and the raw submission, so anything beyond comments",
            "and whitespace is rejected before it can be committed.",
            "",
            "The repo fills itself. A GitHub Action fetches new submissions daily; a",
            "scheduled Claude routine writes the notes. See",
            "[docs/ARCHITECTURE.md](docs/ARCHITECTURE.md).",
            "",
            "**%d problem%s** — %s"
            % (len(problems), "" if len(problems) == 1 else "s", tally or "none yet"),
            "",
            "| # | Problem | Difficulty | Topics | Solved | Runtime |",
            "| --: | --- | --- | --- | --- | --- |",
            *rows,
            "",
            "Other views: [by topic](indexes/by-topic.md) ·",
            "[by difficulty](indexes/by-difficulty.md) ·",
            "[review queue](indexes/review-queue.md)",
            "",
            "Problem statements are my own short restatements, never LeetCode's text, with a",
            "link to the original. Licensed MIT (the notes and code, not the problems).",
            "",
        ]
    )


def render_by_topic(problems) -> str:
    topics = defaultdict(list)
    for entry in problems.values():
        for topic in entry["topics"]:
            topics[topic].append(entry)

    lines = ["# By topic", "", GENERATED_NOTE, ""]
    if not topics:
        lines += ["Nothing solved yet.", ""]
        return "\n".join(lines)

    for topic in sorted(topics, key=lambda t: (-len(topics[t]), t)):
        entries = sorted(
            topics[topic],
            key=lambda e: int(e["frontendId"]) if e["frontendId"].isdigit() else 10**9,
        )
        lines.append("## %s (%d)" % (topic, len(entries)))
        lines.append("")
        for entry in entries:
            lines.append("- %s — %s" % (index_link(entry), entry["difficulty"]))
        lines.append("")
    return "\n".join(lines)


def render_by_difficulty(problems) -> str:
    groups = defaultdict(list)
    for entry in problems.values():
        groups[entry["difficulty"]].append(entry)

    lines = ["# By difficulty", "", GENERATED_NOTE, ""]
    if not groups:
        lines += ["Nothing solved yet.", ""]
        return "\n".join(lines)

    for difficulty in sorted(groups, key=lambda d: DIFFICULTY_ORDER.get(d, 99)):
        entries = sorted(
            groups[difficulty],
            key=lambda e: int(e["frontendId"]) if e["frontendId"].isdigit() else 10**9,
        )
        lines.append("## %s (%d)" % (difficulty, len(entries)))
        lines.append("")
        for entry in entries:
            lines.append(
                "- %s — %s" % (index_link(entry), ", ".join(entry["topics"]))
            )
        lines.append("")
    return "\n".join(lines)


def render_review_queue(problems) -> str:
    today = datetime.now(tz=timezone.utc).date()
    buckets = defaultdict(list)
    for entry in problems.values():
        age = days_since(entry, today)
        for low, high, label in BUCKETS:
            if age >= low and (high is None or age < high):
                buckets[label].append((age, entry))
                break

    lines = [
        "# Review queue",
        "",
        GENERATED_NOTE,
        "",
        "Spaced repetition without any bookkeeping: problems are bucketed purely by how",
        "long ago they were solved, so there is no review state to keep up to date. The",
        "useful habit is to revisit a problem about 1, 3, 7 and 30 days after solving it.",
        "",
        "Work top-down: redo the problem from the **Redo from scratch** checklist in its",
        "README without reading the code first.",
        "",
        "Generated for %s (UTC)." % today.isoformat(),
        "",
    ]

    for _, _, label in BUCKETS:
        entries = sorted(buckets.get(label, []), key=lambda pair: -pair[0])
        lines.append("## %s (%d)" % (label, len(entries)))
        lines.append("")
        if not entries:
            lines.append("_nothing here_")
            lines.append("")
            continue
        for age, entry in entries:
            lines.append(
                "- %s — %s, %s — solved %s (%d day%s ago)"
                % (
                    index_link(entry),
                    entry["difficulty"],
                    ", ".join(entry["topics"]),
                    solved_date(entry),
                    age,
                    "" if age == 1 else "s",
                )
            )
        lines.append("")

    return "\n".join(lines)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not text.endswith("\n"):
        text += "\n"
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    path.write_text(text, encoding="utf-8")
    print("%s  %s" % ("unchanged" if existing == text else "written  ", path.relative_to(REPO)))


def main() -> int:
    problems = load()
    write(REPO / "README.md", render_root(problems))
    write(INDEXES / "by-topic.md", render_by_topic(problems))
    write(INDEXES / "by-difficulty.md", render_by_difficulty(problems))
    write(INDEXES / "review-queue.md", render_review_queue(problems))
    print("rendered %d problem(s)" % len(problems))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
